import type { Product } from "@/types/product";

export const SEED_PRODUCTS: Product[] = [
  {
    slug: "bleu-intense",
    name: "Bleu Intense",
    type: "Eau de Parfum",
    price: 68,
    image:
      "https://images.unsplash.com/photo-1732828912683-57104a2d1b4b?w=800&q=80",
    category: "fragrances",
    gender: "him",
    badge: "BEST SELLER",
    rating: 4,
    reviewCount: 12,
    description:
      "Fresh aquatic notes grounded by vetiver and incense. Clean, sharp, and endlessly wearable.",
    notes: ["Bergamot","Sea Accords","Vetiver","Incense"],
    stock: 16,
    featured: true,
  },
  {
    slug: "cedar-noir",
    name: "Cedar Noir",
    type: "Eau de Toilette",
    price: 71,
    image:
      "https://images.unsplash.com/photo-1732828912093-a776288edfed?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 15,
    description:
      "Smoked cedar and leather with a cool mint opening. Understated and masculine.",
    notes: ["Mint","Cedar","Leather","Tobacco"],
    stock: 17,
    featured: true,
  },
  {
    slug: "obsidian-vetiver",
    name: "Obsidian Vetiver",
    type: "Eau de Parfum",
    price: 74,
    image:
      "https://images.unsplash.com/photo-1577962272294-564f38f71d90?w=800&q=80",
    category: "fragrances",
    gender: "him",
    badge: "NEW",
    rating: 5,
    reviewCount: 18,
    description:
      "Dark vetiver cut with black pepper and cool mineral accords.",
    notes: ["Vetiver","Black Pepper","Mineral","Oakmoss"],
    stock: 18,
    featured: false,
  },
  {
    slug: "night-harbor",
    name: "Night Harbor",
    type: "Eau de Parfum",
    price: 77,
    image:
      "https://images.unsplash.com/photo-1747915725522-cc1dc4b6d809?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 21,
    description:
      "Salty breeze, smoked woods, and a quiet amber base for after-dark.",
    notes: ["Sea Salt","Driftwood","Amber","Smoke"],
    stock: 19,
    featured: false,
  },
  {
    slug: "iron-santal",
    name: "Iron Santal",
    type: "Eau de Parfum",
    price: 80,
    image:
      "https://images.unsplash.com/photo-1767187861728-942f561b7103?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 24,
    description:
      "Metallic sparkle over creamy sandalwood — modern and precise.",
    notes: ["Sandalwood","Metallic Accords","Cedar","Musk"],
    stock: 20,
    featured: false,
  },
  {
    slug: "graphite-smoke",
    name: "Graphite Smoke",
    type: "Eau de Toilette",
    price: 83,
    image:
      "https://images.unsplash.com/photo-1644958292401-c095b23440b7?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 4,
    reviewCount: 27,
    description:
      "Cool graphite, incense, and dry tobacco leaf.",
    notes: ["Graphite","Incense","Tobacco","Violet Leaf"],
    stock: 21,
    featured: false,
  },
  {
    slug: "atlas-leather",
    name: "Atlas Leather",
    type: "Eau de Parfum",
    price: 86,
    image:
      "https://images.unsplash.com/photo-1700522604220-471669e4364c?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 30,
    description:
      "Saddle leather warmed by spice and resinous woods.",
    notes: ["Leather","Cardamom","Labdanum","Guaiac"],
    stock: 22,
    featured: false,
  },
  {
    slug: "pacific-drift",
    name: "Pacific Drift",
    type: "Eau de Toilette",
    price: 89,
    image:
      "https://images.unsplash.com/photo-1700522360590-a913ff2a3d9f?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 33,
    description:
      "Bright citrus over aquatic greens and clean musk.",
    notes: ["Grapefruit","Aquatic Notes","Green Tea","Musk"],
    stock: 23,
    featured: false,
  },
  {
    slug: "black-cypress",
    name: "Black Cypress",
    type: "Eau de Parfum",
    price: 92,
    image:
      "https://images.unsplash.com/photo-1700473209745-1141b0828e06?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 36,
    description:
      "Cypress needles, juniper, and a cool mossy trail.",
    notes: ["Cypress","Juniper","Oakmoss","Pine"],
    stock: 24,
    featured: false,
  },
  {
    slug: "forge-amber",
    name: "Forge Amber",
    type: "Eau de Parfum",
    price: 95,
    image:
      "https://images.unsplash.com/photo-1700473170883-47612d466783?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 39,
    description:
      "Warm amber forged with smoky woods and clove.",
    notes: ["Amber","Clove","Smoked Woods","Benzoin"],
    stock: 25,
    featured: false,
  },
  {
    slug: "volt-cologne",
    name: "Volt Cologne",
    type: "Eau de Toilette",
    price: 98,
    compareAtPrice: 95,
    image:
      "https://images.unsplash.com/photo-1698877360256-bc45ef15e072?w=800&q=80",
    category: "fragrances",
    gender: "him",
    badge: "SALE",
    rating: 4,
    reviewCount: 42,
    description:
      "Electric citrus and mint with a crisp woody finish.",
    notes: ["Lemon","Mint","Cedar","White Musk"],
    stock: 26,
    featured: false,
  },
  {
    slug: "noir-compass",
    name: "Noir Compass",
    type: "Eau de Parfum",
    price: 101,
    image:
      "https://images.unsplash.com/photo-1698877577733-65ae7dee328c?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 45,
    description:
      "Spiced woods and dark chocolate for late evenings.",
    notes: ["Cacao","Cedar","Cinnamon","Patchouli"],
    stock: 27,
    featured: false,
  },
  {
    slug: "steel-fougere",
    name: "Steel Fougère",
    type: "Eau de Toilette",
    price: 69,
    image:
      "https://images.unsplash.com/photo-1698867928110-2408e8e2f44a?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 48,
    description:
      "Classic fougère sharpened with lavender and tonka.",
    notes: ["Lavender","Geranium","Tonka","Coumarin"],
    stock: 28,
    featured: false,
  },
  {
    slug: "timberline",
    name: "Timberline",
    type: "Eau de Parfum",
    price: 72,
    image:
      "https://images.unsplash.com/photo-1747916148863-7164d8920b57?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 51,
    description:
      "Crushed pine, balsam fir, and sun-warmed bark.",
    notes: ["Pine","Fir Balsam","Bark","Moss"],
    stock: 29,
    featured: false,
  },
  {
    slug: "carbon-oud",
    name: "Carbon Oud",
    type: "Extrait de Parfum",
    price: 75,
    image:
      "https://images.unsplash.com/photo-1698877779289-d546e6376001?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 54,
    description:
      "Smoky oud and black pepper — concentrated and bold.",
    notes: ["Oud","Black Pepper","Incense","Leather"],
    stock: 30,
    featured: false,
  },
  {
    slug: "mercantile",
    name: "Mercantile",
    type: "Eau de Parfum",
    price: 78,
    image:
      "https://images.unsplash.com/photo-1747916147834-afe35b0d95ac?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 4,
    reviewCount: 57,
    description:
      "Spiced tea, cedar drawers, and soft suede.",
    notes: ["Black Tea","Cedar","Suede","Cardamom"],
    stock: 31,
    featured: false,
  },
  {
    slug: "riptide",
    name: "Riptide",
    type: "Eau de Toilette",
    price: 81,
    image:
      "https://images.unsplash.com/photo-1775639698865-8621fbccb000?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 60,
    description:
      "Ocean spray, citrus zest, and cool minerals.",
    notes: ["Bergamot","Sea Spray","Salt","Musk"],
    stock: 32,
    featured: false,
  },
  {
    slug: "ash-oak",
    name: "Ash & Oak",
    type: "Eau de Parfum",
    price: 84,
    image:
      "https://images.unsplash.com/photo-1761329842950-f3551938e4da?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 63,
    description:
      "Charred oak, vanilla smoke, and dry woods.",
    notes: ["Oak","Vanilla","Smoke","Sandalwood"],
    stock: 33,
    featured: false,
  },
  {
    slug: "midnight-relay",
    name: "Midnight Relay",
    type: "Eau de Parfum",
    price: 87,
    image:
      "https://images.unsplash.com/photo-1655500064410-95e2f2c7b769?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 66,
    description:
      "Peppercorn, incense, and a sleek woody drydown.",
    notes: ["Pink Pepper","Incense","Vetiver","Amber"],
    stock: 34,
    featured: false,
  },
  {
    slug: "concrete-bloom",
    name: "Concrete Bloom",
    type: "Eau de Toilette",
    price: 90,
    image:
      "https://images.unsplash.com/photo-1618942270792-5d0e8a89a9da?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 69,
    description:
      "Urban greens, citrus, and clean concrete-cool musk.",
    notes: ["Fig Leaf","Citrus","Musk","Cedar"],
    stock: 35,
    featured: false,
  },
  {
    slug: "northbound",
    name: "Northbound",
    type: "Eau de Parfum",
    price: 93,
    image:
      "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 4,
    reviewCount: 72,
    description:
      "Icy mint, arctic woods, and pale amber.",
    notes: ["Mint","Birch","Amber","Musk"],
    stock: 36,
    featured: false,
  },
  {
    slug: "saddle-smoke",
    name: "Saddle & Smoke",
    type: "Eau de Parfum",
    price: 96,
    image:
      "https://images.unsplash.com/photo-1774682060992-46c7e9f2e50b?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 75,
    description:
      "Worn leather, tobacco absolute, and soft smoke.",
    notes: ["Leather","Tobacco","Smoke","Vanilla"],
    stock: 37,
    featured: false,
  },
  {
    slug: "kiln-vetiver",
    name: "Kiln Vetiver",
    type: "Eau de Parfum",
    price: 99,
    image:
      "https://images.unsplash.com/photo-1763631403216-8d193008481e?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 78,
    description:
      "Baked earth, vetiver root, and warm spice.",
    notes: ["Vetiver","Earth","Nutmeg","Woods"],
    stock: 38,
    featured: false,
  },
  {
    slug: "harbor-ink",
    name: "Harbor Ink",
    type: "Eau de Toilette",
    price: 102,
    image:
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 81,
    description:
      "Ink-dark woods with a fresh marine opening.",
    notes: ["Marine","Ink Accords","Cedar","Musk"],
    stock: 39,
    featured: false,
  },
  {
    slug: "ridge-pepper",
    name: "Ridge Pepper",
    type: "Eau de Parfum",
    price: 70,
    image:
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 5,
    reviewCount: 84,
    description:
      "Cracked pepper, juniper berry, and dry cedar.",
    notes: ["Pepper","Juniper","Cedar","Amber"],
    stock: 40,
    featured: false,
  },
  {
    slug: "oblique-blue",
    name: "Oblique Blue",
    type: "Eau de Parfum",
    price: 73,
    image:
      "https://images.unsplash.com/photo-1666621630026-862eea07236c?w=800&q=80",
    category: "fragrances",
    gender: "him",
    rating: 4,
    reviewCount: 87,
    description:
      "Cool indigo florals for him — iris and woods.",
    notes: ["Iris","Violet","Woods","Musk"],
    stock: 41,
    featured: false,
  },
  {
    slug: "quarry",
    name: "Quarry",
    type: "Eau de Toilette",
    price: 76,
    image:
      "https://images.unsplash.com/photo-1458538977777-0549b2370168?w=800&q=80",
    category: "new-arrivals",
    gender: "him",
    rating: 5,
    reviewCount: 90,
    description:
      "Mineral stone, citrus peel, and pale woods.",
    notes: ["Mineral","Bergamot","Woods","Musk"],
    stock: 42,
    featured: false,
  },
  {
    slug: "ember-line",
    name: "Ember Line",
    type: "Eau de Parfum",
    price: 79,
    image:
      "https://images.unsplash.com/photo-1543422655-ac1c6ca993ed?w=800&q=80",
    category: "new-arrivals",
    gender: "him",
    rating: 5,
    reviewCount: 93,
    description:
      "Embers, resin, and a long woody trail.",
    notes: ["Resin","Ember","Cedar","Benzoin"],
    stock: 43,
    featured: false,
  },
  {
    slug: "pilot-spice",
    name: "Pilot Spice",
    type: "Eau de Parfum",
    price: 82,
    image:
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&q=80",
    category: "new-arrivals",
    gender: "him",
    rating: 5,
    reviewCount: 96,
    description:
      "Cardamom cockpit spice with leather and woods.",
    notes: ["Cardamom","Leather","Cedar","Amber"],
    stock: 44,
    featured: false,
  },
  {
    slug: "darkroom",
    name: "Darkroom",
    type: "Extrait de Parfum",
    price: 85,
    image:
      "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=800&q=80",
    category: "new-arrivals",
    gender: "him",
    rating: 5,
    reviewCount: 99,
    description:
      "Intimate woods, incense, and black musk.",
    notes: ["Incense","Black Musk","Woods","Oud"],
    stock: 45,
    featured: false,
  },
  {
    slug: "rose-lumiere",
    name: "Rose Lumière",
    type: "Eau de Parfum",
    price: 72,
    image:
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80",
    category: "fragrances",
    gender: "her",
    badge: "NEW",
    rating: 5,
    reviewCount: 18,
    description:
      "Luminous rose petals meet soft musk and a whisper of citrus — romantic and unforgettable.",
    notes: ["Damask Rose","Bergamot","White Musk","Peony"],
    stock: 20,
    featured: true,
  },
  {
    slug: "velvet-orchid",
    name: "Velvet Orchid",
    type: "Eau de Parfum",
    price: 76,
    image:
      "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 20,
    description:
      "Exotic orchid and plum over a soft suede base. Sensual without being loud.",
    notes: ["Orchid","Plum","Suede","Tonka"],
    stock: 21,
    featured: true,
  },
  {
    slug: "pink-peony",
    name: "Pink Peony",
    type: "Eau de Parfum",
    price: 80,
    image:
      "https://images.unsplash.com/photo-1583394432927-30ce301d5ddf?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 22,
    description:
      "Dewy peony and soft pear over a creamy musk veil.",
    notes: ["Peony","Pear","Musk","Rose"],
    stock: 22,
    featured: false,
  },
  {
    slug: "silk-magnolia",
    name: "Silk Magnolia",
    type: "Eau de Parfum",
    price: 84,
    image:
      "https://images.unsplash.com/photo-1631701258677-758ed94f2611?w=800&q=80",
    category: "fragrances",
    gender: "her",
    badge: "BEST SELLER",
    rating: 5,
    reviewCount: 24,
    description:
      "Creamy magnolia, white tea, and a satin musk trail.",
    notes: ["Magnolia","White Tea","Musk","Sandalwood"],
    stock: 23,
    featured: false,
  },
  {
    slug: "cherry-blush",
    name: "Cherry Blush",
    type: "Eau de Toilette",
    price: 88,
    image:
      "https://images.unsplash.com/photo-1618436623771-29df2e27f809?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 26,
    description:
      "Juicy cherry blossom with soft almond and vanilla.",
    notes: ["Cherry Blossom","Almond","Vanilla","Musk"],
    stock: 24,
    featured: false,
  },
  {
    slug: "petal-cachet",
    name: "Petal Cachet",
    type: "Eau de Parfum",
    price: 92,
    image:
      "https://images.unsplash.com/photo-1590019370947-a9fc6d47b4d0?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 28,
    description:
      "Crushed rose petals, lychee, and radiant musk.",
    notes: ["Rose","Lychee","Musk","Peony"],
    stock: 25,
    featured: false,
  },
  {
    slug: "ivory-jasmine",
    name: "Ivory Jasmine",
    type: "Eau de Parfum",
    price: 96,
    image:
      "https://images.unsplash.com/photo-1595425959632-34f2822322ce?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 30,
    description:
      "Night jasmine wrapped in soft vanilla and woods.",
    notes: ["Jasmine","Vanilla","Sandalwood","Musk"],
    stock: 26,
    featured: false,
  },
  {
    slug: "coral-neroli",
    name: "Coral Neroli",
    type: "Eau de Toilette",
    price: 100,
    image:
      "https://images.unsplash.com/photo-1630573133526-8d090e0269af?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 32,
    description:
      "Sunny neroli, orange blossom, and light musk.",
    notes: ["Neroli","Orange Blossom","Bergamot","Musk"],
    stock: 27,
    featured: false,
  },
  {
    slug: "fleur-de-soie",
    name: "Fleur de Soie",
    type: "Eau de Parfum",
    price: 104,
    image:
      "https://images.unsplash.com/photo-1760920248537-c1185bbc5c61?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 34,
    description:
      "Silken florals with a whisper of iris and powder.",
    notes: ["Iris","Rose","Powder","Musk"],
    stock: 28,
    featured: false,
  },
  {
    slug: "moonlit-gardenia",
    name: "Moonlit Gardenia",
    type: "Eau de Parfum",
    price: 75,
    image:
      "https://images.unsplash.com/photo-1773527142301-9aa77252e5c2?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 36,
    description:
      "Creamy gardenia under moonlight — soft and luminous.",
    notes: ["Gardenia","Tuberose","Musk","Sandalwood"],
    stock: 29,
    featured: false,
  },
  {
    slug: "ruby-tuberose",
    name: "Ruby Tuberose",
    type: "Eau de Parfum",
    price: 79,
    image:
      "https://images.unsplash.com/photo-1767290736754-1fc7a35a38b0?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 38,
    description:
      "Bold tuberose with raspberry and soft woods.",
    notes: ["Tuberose","Raspberry","Woods","Musk"],
    stock: 30,
    featured: false,
  },
  {
    slug: "blush-mimosa",
    name: "Blush Mimosa",
    type: "Eau de Toilette",
    price: 83,
    image:
      "https://images.unsplash.com/photo-1763987300634-7b0822cbf390?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 40,
    description:
      "Sunny mimosa fluff over soft musk and citrus.",
    notes: ["Mimosa","Citrus","Musk","Honey"],
    stock: 31,
    featured: false,
  },
  {
    slug: "pearl-iris",
    name: "Pearl Iris",
    type: "Eau de Parfum",
    price: 87,
    compareAtPrice: 98,
    image:
      "https://images.unsplash.com/photo-1622916132646-50a2a6fe9b9a?w=800&q=80",
    category: "fragrances",
    gender: "her",
    badge: "SALE",
    rating: 5,
    reviewCount: 42,
    description:
      "Powdery iris, violet, and cool pale woods.",
    notes: ["Iris","Violet","Woods","Musk"],
    stock: 32,
    featured: false,
  },
  {
    slug: "sugar-peony",
    name: "Sugar Peony",
    type: "Eau de Parfum",
    price: 91,
    image:
      "https://images.unsplash.com/photo-1588514912908-8f5891714f8d?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 44,
    description:
      "Sweet peony with soft caramel and white musk.",
    notes: ["Peony","Caramel","Musk","Vanilla"],
    stock: 33,
    featured: false,
  },
  {
    slug: "lace-lily",
    name: "Lace & Lily",
    type: "Eau de Parfum",
    price: 95,
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 46,
    description:
      "White lily, soft lacey musk, and clean woods.",
    notes: ["Lily","Musk","Woods","Bergamot"],
    stock: 34,
    featured: false,
  },
  {
    slug: "amour-framboise",
    name: "Amour Framboise",
    type: "Eau de Toilette",
    price: 99,
    image:
      "https://images.unsplash.com/photo-1761937841527-fac9281e53fa?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 48,
    description:
      "Raspberry sparkle with rose water and soft cream.",
    notes: ["Raspberry","Rose","Cream","Musk"],
    stock: 35,
    featured: false,
  },
  {
    slug: "golden-ylang",
    name: "Golden Ylang",
    type: "Eau de Parfum",
    price: 103,
    image:
      "https://images.unsplash.com/photo-1769981287706-0a300ee2fe69?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 50,
    description:
      "Tropical ylang-ylang warmed by vanilla and benzoin.",
    notes: ["Ylang-Ylang","Vanilla","Benzoin","Musk"],
    stock: 36,
    featured: false,
  },
  {
    slug: "soft-cashmere",
    name: "Soft Cashmere",
    type: "Eau de Parfum",
    price: 74,
    image:
      "https://images.unsplash.com/photo-1631701108330-7c9467e2c550?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 52,
    description:
      "Cashmere woods, soft florals, and cozy musk.",
    notes: ["Cashmere Wood","Florals","Musk","Vanilla"],
    stock: 37,
    featured: false,
  },
  {
    slug: "dawn-magnolia",
    name: "Dawn Magnolia",
    type: "Eau de Toilette",
    price: 78,
    image:
      "https://images.unsplash.com/photo-1514348871858-1d3c20902571?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 54,
    description:
      "Fresh morning magnolia with green dew and citrus.",
    notes: ["Magnolia","Green Notes","Citrus","Musk"],
    stock: 38,
    featured: false,
  },
  {
    slug: "rose-atelier",
    name: "Rosé Atelier",
    type: "Eau de Parfum",
    price: 82,
    image:
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 56,
    description:
      "Rosé champagne sparkle with rose and soft musk.",
    notes: ["Rose","Champagne Accords","Musk","Peach"],
    stock: 39,
    featured: false,
  },
  {
    slug: "whisper-lilac",
    name: "Whisper Lilac",
    type: "Eau de Parfum",
    price: 86,
    image:
      "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 58,
    description:
      "Delicate lilac and soft powder over white musk.",
    notes: ["Lilac","Powder","Musk","Iris"],
    stock: 40,
    featured: false,
  },
  {
    slug: "crystal-bloom",
    name: "Crystal Bloom",
    type: "Eau de Parfum",
    price: 90,
    image:
      "https://images.unsplash.com/photo-1622618991746-fe6004db3a47?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 60,
    description:
      "Clear floral bouquet with a sparkling citrus top.",
    notes: ["Florals","Bergamot","Musk","Sandalwood"],
    stock: 41,
    featured: false,
  },
  {
    slug: "satin-rose",
    name: "Satin Rose",
    type: "Eau de Parfum",
    price: 94,
    image:
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 62,
    description:
      "Satin-soft rose absolute with warm amber light.",
    notes: ["Rose Absolute","Amber","Musk","Vanilla"],
    stock: 42,
    featured: false,
  },
  {
    slug: "honey-orchid",
    name: "Honey Orchid",
    type: "Eau de Parfum",
    price: 98,
    image:
      "https://images.unsplash.com/photo-1535683577427-740aaac4ec25?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 64,
    description:
      "Honeyed orchid and soft plum over tonka.",
    notes: ["Orchid","Honey","Plum","Tonka"],
    stock: 43,
    featured: false,
  },
  {
    slug: "belle-de-nuit",
    name: "Belle de Nuit",
    type: "Eau de Parfum",
    price: 102,
    image:
      "https://images.unsplash.com/photo-1768025719875-48ed072f3084?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 66,
    description:
      "Night-blooming florals with soft incense glow.",
    notes: ["Night Bloom","Incense","Musk","Woods"],
    stock: 44,
    featured: false,
  },
  {
    slug: "petal-milk",
    name: "Petal Milk",
    type: "Eau de Toilette",
    price: 73,
    image:
      "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80",
    category: "fragrances",
    gender: "her",
    rating: 5,
    reviewCount: 68,
    description:
      "Milky florals, soft almond, and clean musk.",
    notes: ["Florals","Almond","Milk Accords","Musk"],
    stock: 45,
    featured: false,
  },
  {
    slug: "iris-veil",
    name: "Iris Veil",
    type: "Eau de Parfum",
    price: 77,
    image:
      "https://images.unsplash.com/photo-1593487568720-92097fb460fb?w=800&q=80",
    category: "new-arrivals",
    gender: "her",
    rating: 5,
    reviewCount: 70,
    description:
      "A soft iris veil with violet leaf and musk.",
    notes: ["Iris","Violet Leaf","Musk","Woods"],
    stock: 46,
    featured: false,
  },
  {
    slug: "blooming-boudoir",
    name: "Blooming Boudoir",
    type: "Eau de Parfum",
    price: 81,
    image:
      "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800&q=80",
    category: "new-arrivals",
    gender: "her",
    rating: 5,
    reviewCount: 72,
    description:
      "Powdery florals, soft woods, and intimate musk.",
    notes: ["Powder","Florals","Woods","Musk"],
    stock: 47,
    featured: false,
  },
  {
    slug: "pink-amber",
    name: "Pink Amber",
    type: "Eau de Parfum",
    price: 85,
    image:
      "https://images.unsplash.com/photo-1621814374283-57cc5d0d39c2?w=800&q=80",
    category: "new-arrivals",
    gender: "her",
    rating: 5,
    reviewCount: 74,
    description:
      "Soft pink florals melted into warm amber.",
    notes: ["Pink Florals","Amber","Vanilla","Musk"],
    stock: 48,
    featured: false,
  },
  {
    slug: "etoile-florale",
    name: "Étoile Florale",
    type: "Extrait de Parfum",
    price: 89,
    image:
      "https://images.unsplash.com/photo-1705338670422-01133208eab9?w=800&q=80",
    category: "new-arrivals",
    gender: "her",
    rating: 5,
    reviewCount: 76,
    description:
      "Concentrated floral star — rose, jasmine, and musk.",
    notes: ["Rose","Jasmine","Musk","Sandalwood"],
    stock: 49,
    featured: false,
  },
  {
    slug: "noir-oud",
    name: "Noir Oud",
    type: "Eau de Parfum",
    price: 89,
    image:
      "https://images.unsplash.com/photo-1718466044521-d38654f3ba0a?w=800&q=80",
    category: "fragrances",
    gender: "unisex",
    badge: "BEST SELLER",
    rating: 5,
    reviewCount: 128,
    description:
      "A deep, smoky oud wrapped in warm amber and dark woods. Bold enough for night, refined enough for every day.",
    notes: ["Oud","Amber","Sandalwood","Black Pepper"],
    stock: 42,
    featured: true,
  },
  {
    slug: "santal-blanc",
    name: "Santal Blanc",
    type: "Eau de Parfum",
    price: 85,
    image:
      "https://images.unsplash.com/photo-1723391962154-8a2b6299bc09?w=800&q=80",
    category: "fragrances",
    gender: "unisex",
    badge: "BEST SELLER",
    rating: 5,
    reviewCount: 96,
    description:
      "Creamy sandalwood softened by vanilla and iris. A modern classic with quiet confidence.",
    notes: ["Sandalwood","Vanilla","Iris","Cedar"],
    stock: 38,
    featured: true,
  },
  {
    slug: "ambre-royale",
    name: "Ambre Royale",
    type: "Eau de Parfum",
    price: 90,
    image:
      "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&q=80",
    category: "fragrances",
    gender: "unisex",
    badge: "NEW",
    rating: 5,
    reviewCount: 41,
    description:
      "Resinous amber layered with honey and labdanum. Opulent warmth that lingers for hours.",
    notes: ["Amber","Honey","Labdanum","Benzoin"],
    stock: 29,
    featured: false,
  },
  {
    slug: "citrus-soleil",
    name: "Citrus Soleil",
    type: "Eau de Toilette",
    price: 68,
    image:
      "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80",
    category: "new-arrivals",
    gender: "unisex",
    badge: "NEW",
    rating: 5,
    reviewCount: 22,
    description:
      "Sun-bright citrus and green tea. The scent of a late-afternoon terrace.",
    notes: ["Lemon","Neroli","Green Tea","White Woods"],
    stock: 60,
    featured: false,
  },
  {
    slug: "atelier-exclusive",
    name: "Atelier Exclusive",
    type: "Extrait de Parfum",
    price: 120,
    image:
      "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    category: "collections",
    gender: "unisex",
    badge: "NEW",
    rating: 5,
    reviewCount: 12,
    description:
      "Our limited atelier extract — concentrated, intimate, and made in small batches.",
    notes: ["Saffron","Oud","Rose Absolute","Mysore Sandalwood"],
    stock: 10,
    featured: false,
  },
  {
    slug: "mirage-trio",
    name: "Mirage Trio Gift Set",
    type: "Gift Set",
    price: 149,
    compareAtPrice: 175,
    image:
      "https://images.unsplash.com/photo-1718466044521-d38654f3ba0a?w=800&q=80",
    category: "gift-sets",
    gender: "unisex",
    badge: "SALE",
    rating: 5,
    reviewCount: 35,
    description:
      "Three 30ml favorites — Noir Oud, Rose Lumière, and Santal Blanc — curated for gifting.",
    notes: ["Oud","Rose","Sandalwood"],
    stock: 25,
    featured: false,
  },
  {
    slug: "her-collection",
    name: "For Her Collection",
    type: "Gift Set",
    price: 165,
    image:
      "https://images.unsplash.com/photo-1673710672680-944563ff9cce?w=800&q=80",
    category: "gift-sets",
    gender: "her",
    rating: 5,
    reviewCount: 19,
    description:
      "A trio of feminine signatures: Rose Lumière, Velvet Orchid, and a travel atomizer.",
    notes: ["Rose","Orchid","Musk"],
    stock: 18,
    featured: false,
  },
  {
    slug: "him-collection",
    name: "For Him Collection",
    type: "Gift Set",
    price: 165,
    image:
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80",
    category: "gift-sets",
    gender: "him",
    rating: 5,
    reviewCount: 17,
    description:
      "Bleu Intense, Cedar Noir, and a leather travel case — ready to gift.",
    notes: ["Vetiver","Cedar","Leather"],
    stock: 16,
    featured: false,
  },
];

export function filterProducts(
  products: Product[],
  params: {
    category?: string;
    gender?: string;
    badge?: string;
    featured?: boolean;
  },
) {
  return products.filter((p) => {
    if (params.featured && !p.featured) return false;
    if (params.category && p.category !== params.category) return false;
    if (params.gender && p.gender !== params.gender && p.gender !== "unisex")
      return false;
    if (params.badge && p.badge !== params.badge) return false;
    return true;
  });
}

export function formatPrice(amount: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}
